Todo feature
tahiry-dev/todo-app pull request #1
Opened 2021-03-03 11:10 UTC by tahiry-dev

- Create the appearance of the page
- Compile it with Webpack
- Create different components that allow the app to behave correctly
- Use localStorage to store data

2021-03-03 11:29 UTC, mikenath223 requested changes
### Hello @tahiry-dev  👋

**You've done pretty well here and a nice UI concept also. 👌**

However, let's make a couple of changes.

- [ ] The localStorage wasn't configured properly in the project. The expected behavior is that after creating a category or todo item, and refreshing the page the todo item and/or category should still remain on the page. Please fix this.

- Please refer to other comments on the code.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-03-03 11:31 UTC, mikenath223 commented on src/index.js
> +      console.log(e.target.parentElement.parentElement);
- [ ] Kindly remove this console log statement here. Debugging code shouldn't be committed.

2021-03-03 11:31 UTC, mikenath223 commented on src/components/toDoController.js
> +      console.log(toDoArray[i].toDos);
- [ ] Also please remove this console.log statement here.

2021-03-03 11:33 UTC, mikenath223 commented on src/components/toDoController.js
> +export function setActiveList(targetListId) {
- [ ] Please change this and **all** other regular functions to es6 arrow function syntax.

2021-03-08 08:47 UTC, arslanbisharat approved these changes
# Approved

Thank you for submitting this Pull Request. And thank you for making the requested changes.  Your project is approved. 

Best,
Arslan Bisharat

2021-03-08 08:52 UTC, merged